---
title: "Introduction"
home: true
numbered: false
number-sections: false
---

The global geospatial solutions market was valued at USD 626 billion in 2024; with a 13% projected annual growth rate, it is expected to reach \$2155 billion by 2034 (Prescient and Strategic Intelligence, 2024). Globally, many governments are funding the development of geospatial infrastructure and promoting the geospatial solutions. A large number of students trained in geospatial sciences will be needed to support the steady demand for the workforce.

Geospatial science is a true interdisciplinary subject that covers a broad range of topics in both natural and social sciences and technologies. Usually, it is difficult to find one suitable textbook to cover all the materials in Geographical information system (GIS), global navigation satellite system (GNSS), remote sensing, and their broad applications. Requiring multiple textbooks will further increase the cost of taking these classes on students.

To address this challenge, we plan to develop this Open Educational Resource (OER) by forming a team with distinct backgrounds spanning remote sensing, urban geography, historical geography, and sustainability in urban and rural areas. Our goal is to develop OER that can be used in introductory and intermediate levels geospatial science courses, covering concepts of GIS and remote sensing and their applications in a wide range of disciplines.

## Copyright, License & Third-Party Materials

This work was developed by Ran Wang, Xiaomeng Li, and Andrew Husa, with support from University of Nebraska-Lincoln Libraries.

*Suggested citation:* *Wang, R., Li, X., Husa, A. (2026) Mapping the world: An open textbook on GIS and remote sensing. Available at: https://open-spatial-science.github.io/intro-gis-rs/*

**License**

Except where otherwise noted, this work is licensed under the Creative Commons Attribution-ShareAlike 4.0 International License (CC BY-SA 4.0; [Full license text](https://creativecommons.org/licenses/by-sa/4.0/)). You are free to share and adapt the material, provided you give appropriate credit and distribute any derivative works under the same license.

**Third-party materials**

ArcGIS® software screenshots are the intellectual property of Esri and are used herein with permission. Copyright © Esri. All rights reserved.

Unless otherwise indicated, third-party texts, images, and other materials quoted in these materials are included on the basis of fair use as described in the Code of Best Practices for Fair Use in Open Education.

## Acknowledgement

This Open Educational Resource (OER) was made possible in part through funding from the University of Nebraska-Lincoln Libraries [OER STAR Seed Grant](https://teaching.unl.edu/star-oer/seed-grants/). We also sincerely appreciate the support from the School of Natural Reources and School of Global Integrative Studies at UNL, and the US Department of Agriculture's Agricultural Research Service (USDA-ARS) Partnerships for Data Innovations (PDI) initiative.

## Feedback & Contributions

**Help Improve This Book**

This textbook is an open educational resource and is intended to evolve over time. We welcome feedback from instructors, students, and readers.

If you notice an error, have a suggestion, or would like to propose new content, the best way to contribute is through our GitHub repository:

- Report issues (typos, errors, unclear explanations)

- Suggest enhancements or additional examples

- Request new topics or features

Please visit the [repository](https://github.com/open-spatial-science/intro-gis-rs) and open an issue to get started.

**Adopting This Textbook**

Instructors are welcome and encouraged to adopt this book in their courses.

You are free to:

- Use the book as-is

- Adapt or remix the content to suit your course

- Share your adapted versions with your students

If you adopt this textbook, we would appreciate hearing from you. This helps us understand how the book is being used and prioritize improvements. If you adopt this textbook or want to provide feedback, please fill out this form:

[Share your adoption and feedback](https://docs.google.com/forms/d/e/1FAIpQLSd-ySUsZqbJNrq4Y17G3bKhsHGILpX224AEoX5cWV14m2eGCw/formResponse)

**Contact**

If you prefer to reach out directly, you may [contact the authors](mailto:ranwangrs@gmail.com)